# Generated by Django 4.2.11 on 2024-04-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustoGes', '0002_cliente_rename_responsable_tarea_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(default=0.0005),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=0.0005),
        ),
    ]
