# Generated by Django 4.2.11 on 2024-05-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustoGes', '0003_alter_empleado_created_alter_empleado_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='deustoges', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='username',
            field=models.CharField(default='deustoges', max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='password',
            field=models.CharField(default='deustoges', max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='username',
            field=models.CharField(default='deustoges', max_length=50),
        ),
    ]
