# Generated by Django 4.2.11 on 2024-05-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustoGes', '0004_cliente_password_cliente_username_empleado_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
