# Generated by Django 4.2.11 on 2024-05-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustoGes', '0005_alter_cliente_username_alter_empleado_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='password',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='username',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='password',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='username',
            new_name='usuario',
        ),
    ]
